name: Mada
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: 3.3.1
  collection: ^1.18.0
  data_table_2: 2.5.10
  dropdown_button2: 2.3.9
  equatable: 2.0.5
  expandable: 5.0.1
  sign_in_with_apple: ^6.1.4
#  file_picker: 8.0.3
  firebase_auth: ^5.4.1
  firebase_auth_platform_interface: ^7.5.1
  firebase_auth_web: ^5.13.7
  firebase_core: ^3.11.0
  firebase_core_platform_interface: ^5.3.1
  firebase_core_web: ^2.19.0
  firebase_performance: ^0.10.1+2
  firebase_performance_platform_interface: ^0.1.5+1
  firebase_performance_web: ^0.1.7+7
  firebase_storage: ^12.4.1
  firebase_storage_platform_interface: ^5.2.1
  firebase_storage_web: ^3.10.8
  fl_chart: 0.68.0
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_credit_card: 4.0.1
  flutter_plugin_android_lifecycle: 2.0.20
  flutter_rating_bar: 4.0.1
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 14.2.9
  flutter_web_plugins:
    sdk: flutter
  google_fonts: 6.1.0
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.7.6
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  http: 1.2.1
  image_picker: 1.0.4
  image_picker_android: 0.8.8
  image_picker_for_web: 3.0.1
  image_picker_ios: 0.8.8+2
  image_picker_platform_interface: ^2.10.0
  infinite_scroll_pagination: 4.0.0
  intl: 0.19.0
  json_path: 0.7.2
  js: ^0.6.3
  mapbox_search: 4.2.2
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  percent_indicator: 4.2.2
  photo_view: 0.14.0
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  rxdart: 0.27.7
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sqflite: 2.2.6
  stop_watch_timer: 3.0.2
  timeago: 3.6.1
  url_launcher: 6.3.0
  video_player: 2.8.6
  flutter_svg: 2.0.9
  easy_debounce: 2.0.1
#  google_static_maps_controller: ^1.1.0
  info_popup: ^4.3.1
  image_network: ^2.5.6
  universal_html: ^2.2.4
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_widget_from_html: ^0.15.3
  geolocator: ^12.0.0
  file_picker: ^8.0.7
  panorama: ^0.4.1
  image: ^4.2.0
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.0
  country_picker: ^2.0.26
  country_flags: ^3.0.0
  client_information: ^2.1.4
  firebase_messaging: ^15.2.1
  fluttertoast: ^8.2.8
  package_info_plus: ^8.0.2
  smooth_page_indicator: ^1.2.0+3




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  gap: ^3.0.1
  dio: ^5.8.0+1
  get: ^4.7.2

dependency_overrides:
  http: ^1.3.0
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

