name: Mada
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  http: 1.2.1
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+22
  image_picker_ios: ^0.8.12+2
  intl: 0.19.0
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.16
  path_provider_foundation: ^2.4.1
  path_provider_platform_interface: 2.1.2
  percent_indicator: ^4.2.4
  photo_view: ^0.15.0
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  shared_preferences: 2.5.2
  shared_preferences_android: ^2.4.8
  shared_preferences_foundation: ^2.5.4
  shared_preferences_platform_interface: ^2.4.1
  stop_watch_timer: ^3.2.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
#  video_cached_player: ^2.4.9+1
  flutter_svg: ^2.0.17
  easy_debounce: ^2.0.3
  info_popup: ^4.3.1
  image_network: ^2.5.6
  universal_html: ^2.2.4
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  modal_bottom_sheet: ^3.0.0
#  flutter_widget_from_html: ^0.16.0
  cached_network_image: ^3.4.1
  geolocator: ^13.0.2
  file_picker: ^9.0.2
  image: ^4.2.0
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.0
  country_picker: ^2.0.26
  country_flags: ^3.0.0
  client_information: ^2.1.4
  fluttertoast: ^8.2.8
  package_info_plus: ^8.0.2
  smooth_page_indicator: ^1.2.0+3
  flutter_email_sender: ^7.0.0
  jwt_decoder: ^2.0.1
  image_cropper: ^9.0.0
  webview_flutter: ^4.10.0
  share_plus: ^10.1.4
  flutter_cached_pdfview: ^0.4.2
  permission_handler: ^11.4.0
  location: ^6.0.2
  qr_flutter: ^4.1.0
  flutter_html: ^3.0.0
  flick_video_player: ^0.9.0
  pdf: ^3.10.4
  html_unescape: ^2.0.0








  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  gap: ^3.0.1
  dio: ^5.8.0+1
  flutter_smart_dialog: ^4.9.8+7
  flutter_local_notifications: ^19.0.0

dependency_overrides:
  http: ^1.3.0
  uuid: ^4.0.0
  win32: 5.5.1
#  wakelock: 0.6.2

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

